### ISSUE TITLE
Recycle instances after deployment rather than DeleteAndCreate?

### ISSUE THREAD

**Issue by dmarlow** [Microsoft/azure-ssl-configure#1]
Wouldn't it be better to recycle the instances after a deployment that has AzureDeploymentReplacementMethod set to AutomaticUpgrade rather than setting it to DeleteAndCreate? This way, you don't have to change it back later? I don't know, just an idea I had...

**Comment by qinxgit** [comment]
Yes, you are right. Updated.

**Comment by qinxgit** [comment]
It is fixed.
