### ISSUE TITLE
SSLConfigure.cmd exit code - 255

### ISSUE THREAD

**Issue by Mohammad-Moussa-Haidar** [Microsoft/azure-ssl-configure#2]
I am getting this error, any help please 
Details:  Last exit time: [2018/10/30, 08:14:53.989]. Last exit code: -2147467259. Last startup task error: name - "E:\approot\bin\Startup\SSLConfigure.cmd" , exit code - 255.

**Comment by qinxgit** [comment]
Sometimes you need to update the relative path of the PS1 in the cmd file, Changed the relative path to use the bat file's path instead. In that way, as long as the bat file is with the bat file, it should work.
